### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by vdurante** [hundertzehn/mocoapp-api-docs#269]
I am studying the API docs from MOCO and have a few questions. Would appreciate if someone could help me out:

- Is it possible to update an invoice through the API? I saw on the web there is an internal PUT endpoint, but I couldn't find a public on on the API docs. I want to add new items (positions) to the invoice after I created it.
- Invoices have a few required fields, but I am unsure where to fetch the possible values for a few of those:
  - currency - is there an endpoint I could use to fetch the currencies that could be used?
  - tax - is there an endpoint I could use to fetch the tax values that could be used?

Thanks in advance for the help!

**Comment by agileapplications** [comment]
Hi @vdurante 

Thanks for sharing your questions.

- We don't have yet an update for invoices. It's on our list. You are not the only one.
- The endpoints for tax/currency are not yet available, but since there are normally very little entries, you should be fine with passing "EUR", "USD" specifically.

Sorry that I don't have more compelling answers atm.

Best Tobias

**Comment by vdurante** [comment]
Thanks Tobias!

@agileapplications
