### ISSUE TITLE
[FEATURE REQUEST] - Endpoint to set period lock

### ISSUE THREAD

**Issue by 0x20004** [hundertzehn/mocoapp-api-docs#71]
Hello,

we need an api endpoint so we can automatically set the period lock (Periodensperre).
I didn't found something like that in the docs. Correct me please, if i'm wrong.

Even better would be a setting in the frontend to set a time to lock all changes.
For example a new day begins (00:01) and the period lock is set 48 hours before today.
So all accounts can edit the last two days only.
This shall prevent later manipulation.

Thanks for your help!
Best regards

**Comment by agileapplications** [comment]
Hi @0x20004 

Sorry for the late reply. We will have an upcoming feature change here. You will be able to set a delay instead of fixed dates as well. For example "2 days" which means that time tracking is only allowed within 2 days backwards.

We won't provide an endpoint for now. Should happen this year.

Best Tobias
